### ISSUE TITLE
The spiky platform's platform does not disappear when killed

### ISSUE THREAD

**Issue by sejego** [victords/super-bombinhas#7]
### Problem description

When you shoot down the spiky platform and then immediately jump on it while it is "living its last moments before death" then only the sprite disappears, and you still can jump on the platform.
### Environment

* Lenovo ThinkPad T570
* Pop!_OS 20.04 32GB RAM Intel i5
* Rate of reproduction: 3
* Game level : 1 - 3

### Steps to reproduce

Run and shoot the spiky platform, and when its hit, immediately jump on it. Once the sprite has disappeared, you still can jump from and onto the platform

### Expected result

The monster is completely destroyed and there is no way to jump on his platform. If monster died after you jumped on it, the platform will die and the player will fall down to the ground.

### Actual result

Platform is invisible but still exists, it is possible to jump onto it and from it.

### Visual proof

See picture [here](https://imgur.com/a/HmAWYPe)

**Comment by victords** [comment]
Hi there, thanks for reporting this. I'll fix it as soon as possible.

**Comment by victords** [comment]
Fixed on [v1.4.1](https://github.com/victords/super-bombinhas/releases/tag/v1.4.1). I'll update the binaries in itch.io and Steam shortly.
