### ISSUE TITLE
Name of the bomb starts with lowercase

### ISSUE THREAD

**Issue by sejego** [victords/super-bombinhas#8]
This is a rather small one.

After finishing stage 1 of the game, in the intro to the next stage the name of Bomba Vermelha is written in lowercase.
Screenshot available [here](https://imgur.com/a/u3SfnQG)

Keep up the good work! :)

**Comment by victords** [comment]
Thanks again! I'll fix it soon, but won't create a new release for it, since it's very minor.

**Comment by victords** [comment]
Fixed: https://github.com/victords/super-bombinhas/commit/4c0e7be777dfcad913229a45086ebaf371334661
