### ISSUE TITLE
After receiving Vermelha, Azul cannot pick lifes (hearts) anymore

### ISSUE THREAD

**Issue by sejego** [victords/super-bombinhas#9]
Maybe it is intended functionality, but it seems that there is no way to replenish lives for Azul if you have Vermelha. Only Vermelha can pick up lives and all lives automatically go to his lifebar. Happened on stage 2-1. Link to [screenshot](https://imgur.com/a/OycChfU)

**Comment by victords** [comment]
Yeah, that's intended. The color of the "frame" on the items indicate the color of the bomb that can pick them up. There's actually no Heart item for Bomba Azul - notice that there's no Heart item in the entirety of World 1. On the other hand, Bomba Azul can pick up attack items that Bomba Vermelha can't.

**Comment by sejego** [comment]
Sorry, didn't get that it was intended! Thanks!
